// <auto-generated />
namespace OnlineQuizClasses.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NewPropertyTime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewPropertyTime));
        
        string IMigrationMetadata.Id
        {
            get { return "201807061336081_NewPropertyTime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
